### ISSUE TITLE
...iota.go/kerl/sha3 expects import "golang.org/x/crypto/sha3"

### ISSUE THREAD

**Issue by blumanski** [iotaledger/iota.go#242]
## Bug description

go get github.com/iotaledger/iota.go/api

Error: ../src/github.com/iotaledger/iota.go/kerl/kerl.go:10:2: code in directory /var/www/domain/go/src/github.com/iotaledger/iota.go/kerl/sha3 expects import "golang.org/x/crypto/sha3"

## Version

go version go1.15.1 linux/amd64

## Hardware Specification

Standard linux/ubuntu hosting vps

## Steps To reproduce the bug

go get github.com/iotaledger/iota.go/api

Trying to get started with iota go, any advise how to overcome this error. I tried replacing the import but that didnt work.
I saw the closed issue/request regarding the the sh3 library, but that is 2018.

https://github.com/iotaledger/iota.go/issues/30

Any help welcome

**Comment by jspdown** [comment]
Hello @blumanski. The `go get` command behaviour depends on where you run it. 

Iota has forked `golang.org/x/crypto/sha3` which, like in most `golang.org/x/*` packages, uses a custom import path in order to keep it go gettable no matter where the code is hosted. If you want to read more on this subject: https://golang.org/cmd/go/#hdr-Import_path_checking.

This is done in the following file:

https://github.com/iotaledger/iota.go/blob/7eac7c1cc80b59b7e7c2c285a463c24eccc9ec89/kerl/sha3/doc.go#L62-L66

When you are doing `go get github.com/iotaledger/iota.go/api`, the behaviour will be different following if you are in module-aware mode (when the current directory contains a `go.mod` file) or not. If you are not, go will try to fetch the code from URL specified in the custom import path (here `golang.org/x/crypto/sha3`) but will fail because of import path checking. 

There are 2 solutions to fix this:
- Run the `go get github.com/iotaledger/iota.go/api` in a directory which contains a `go.mod`. As pointed in the README, you have to run `go mod init <your-module-path>` first.
- The iota.go maintainer can remove the `// import "golang.org/x/crypto/sha3"` comment from `kerl/sha3/doc.go`
