### ISSUE TITLE
iota.go masks 404 errors

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iota.go#266]
## Bug description

Instead of responding with a 404, iota.go gives out another error that masks the underlying issue

## Version

`v2.0.0-20210218145050-36683a2a177c`

## Hardware Specification

SpaceX Falcon 9

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

 ```go
    nodeAPI := iota.NewNodeAPI("http://node-url/:14265")   // note the extra slash
	info, err := nodeAPI.Info()
	must(err)
```

## Expected behaviour

Should panic on a 404 error.

## Actual behaviour

Panics on a bad json format.
## Errors

`panic: unable to read error from response body: invalid character 'p' after top-level value`

**Comment by luca-moser** [comment]
In your particular case, the lib is doing the correct thing. As you malformed the URI, you queried something not returning a JSON response (which every route does in our HTTP API), so parsing the response fails and there is no need to return you a 404 because the route is completely wrong to begin with.
